{% set version = "4.6.0" %}

package:
  name: existdb
  version: {{ version }}

source:
  fn: existdb.jar
  url: https://bintray.com/existdb/releases/download_file?file_path=eXist-db-setup-{{ version }}.jar
  sha256: 916d93f5b4ede2c111e3288279fcca5d6baced4b5f02ad8f85d95f7eba686c45

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - openjdk
  run:
    - openjdk

test:
  commands:
    - test -f $PREFIX/share/existdb/start.jar
    - test -f $PREFIX/share/existdb/bin/shutdown.sh     # [unix]
    - test -f $PREFIX/share/existdb/bin/shutdown.bat    # [win]

about:
  home: http://exist-db.org/exist/apps/homepage/index.html
  license: LGPL-2.1
  license_family: LGPL
  summary: 'eXist Native XML Database'
  description: |
    eXist is a high-performance open source native XML database—a 
    NoSQL document database and application platform built entirely 
    around XML technologies. The main homepage for eXist can be found 
    at exist-db.org. This is the GitHub repository of eXist source code, 
    and this page links to resources for downloading, building, and 
    contributing to eXist, below.

extra:
  recipe-maintainers:
    - marcelotrevisani
