travis:
  secure:
    BINSTAR_TOKEN: fXO28O37b2sY37aRGxqyQgLCiysOTJTW7dCYSOobIwjGqJ6AYQzzvQ1iJ37FIvw1dxEo7p46S2BrjOOWg+HAiXGF26iIMpGozcihesH1viDc3mmAEe+VzQf41QEm+BAzjjodMpZkrTCfRMob7e+Q8iPO9L0WEsp+kdgVz9IuRHmNIWvtpc9Q5sxLrUcRvWg15D+Cob4PNRpAkcYkuDEdPofrVufK7NomPm44Kwf21eyLq7pYMByNjD/zthpcxh5zE4vMwmnNnUK9pnRN0YgFiz3FYf+rfe5IVj7rkko+irbN3LBMiQStFqlSf1wmQ3tkA6+ylvaK2JWpovc/290TfNLXIFcrMRIvknyRRkZwSMQwVtBSyaN1NPNInfeW/JLMmCZJyU3wmsdW3bzUPF316/7bk8IS9k6Aip3Xmjcyj4h8Q2Sahtsi1vqmrm3rMa6RABsK4rHH0463u0S5wNvdlu/QftIQgz551K2NykXAC6up4O5mbJ99F/e6hVx7xKo9QkKaGfpCBbd/iOWvIOHrXRrwKrPEiPxdUjDjqjj/lpHgIKCbFzmerso5/DYcUjzKlZe2AkmGwH6jsNlkdEzgYScEhiec0LPXEqQ29L+T0rHbwI9Ap2vN2iZ+QGR+9h/A8OWuB1vs1KmJ3+1kt48Bf94YmXxrZ3YkzRZ+Fw4l0tQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
